// Cada migração roda uma única vez, em ordem. Nunca altere uma migração já publicada:
// crie uma nova no fim da lista.
//
// Convenções:
// - Datas e horários ficam em TEXT com COLLATE "C" (ordenação byte a byte). Assim a comparação
//   entre textos como '2026-10-04T19:00' funciona igual em qualquer servidor Postgres.
//   Horários de evento são "hora local da casa" (YYYY-MM-DDTHH:MM); registros de sistema
//   (created_at etc.) ficam em UTC no formato 'YYYY-MM-DD HH:MM:SS'.
// - Valores em dinheiro são inteiros em centavos.

const TS = `TEXT COLLATE "C" NOT NULL DEFAULT now_text()`;
const D = 'TEXT COLLATE "C"';

export const migrations = [
  {
    version: 1,
    name: 'schema inicial',
    sql: `
      CREATE OR REPLACE FUNCTION now_text() RETURNS text LANGUAGE sql STABLE AS
        $$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') $$;
      CREATE OR REPLACE FUNCTION today_text() RETURNS text LANGUAGE sql STABLE AS
        $$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD') $$;
      CREATE OR REPLACE FUNCTION days_ago_text(n integer) RETURNS text LANGUAGE sql STABLE AS
        $$ SELECT to_char((now() AT TIME ZONE 'UTC') - make_interval(days => n), 'YYYY-MM-DD') $$;

      CREATE TABLE users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE CHECK (email = lower(email)),
        phone TEXT,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL CHECK (role IN ('admin','gerente','financeiro','comercial','operador')),
        active INTEGER NOT NULL DEFAULT 1,
        failed_attempts INTEGER NOT NULL DEFAULT 0,
        locked_until ${D},
        must_change_password INTEGER NOT NULL DEFAULT 0,
        last_login_at ${D},
        created_at ${TS},
        updated_at ${TS}
      );

      CREATE TABLE sessions (
        id TEXT PRIMARY KEY,
        user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        csrf_token TEXT NOT NULL,
        ip TEXT,
        user_agent TEXT,
        created_at ${TS},
        expires_at ${D} NOT NULL
      );
      CREATE INDEX idx_sessions_user ON sessions(user_id);

      CREATE TABLE units (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        location TEXT NOT NULL,
        capacity INTEGER NOT NULL CHECK (capacity > 0),
        color TEXT NOT NULL DEFAULT '#6d5bd0',
        notes TEXT,
        active INTEGER NOT NULL DEFAULT 1,
        created_at ${TS},
        updated_at ${TS}
      );
      CREATE UNIQUE INDEX idx_units_name ON units (lower(name));

      CREATE TABLE clients (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        type TEXT NOT NULL DEFAULT 'PF' CHECK (type IN ('PF','PJ')),
        name TEXT NOT NULL,
        document TEXT,
        email TEXT,
        phone TEXT,
        whatsapp TEXT,
        birth_date ${D},
        address TEXT,
        city TEXT,
        state TEXT,
        source TEXT,
        notes TEXT,
        created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at ${TS},
        updated_at ${TS}
      );
      CREATE INDEX idx_clients_name ON clients(name);

      CREATE TABLE deals (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
        stage TEXT NOT NULL DEFAULT 'novo'
          CHECK (stage IN ('novo','contato','visita','proposta','negociacao','ganho','perdido')),
        value_cents BIGINT NOT NULL DEFAULT 0 CHECK (value_cents >= 0),
        event_type TEXT,
        expected_date ${D},
        guests INTEGER,
        unit_id BIGINT REFERENCES units(id) ON DELETE SET NULL,
        source TEXT,
        owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        lost_reason TEXT,
        notes TEXT,
        closed_at ${D},
        created_at ${TS},
        updated_at ${TS}
      );
      CREATE INDEX idx_deals_stage ON deals(stage);
      CREATE INDEX idx_deals_client ON deals(client_id);

      CREATE TABLE interactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
        deal_id BIGINT REFERENCES deals(id) ON DELETE SET NULL,
        type TEXT NOT NULL CHECK (type IN ('nota','ligacao','whatsapp','email','visita','reuniao')),
        description TEXT NOT NULL,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at ${TS}
      );
      CREATE INDEX idx_interactions_client ON interactions(client_id);

      CREATE TABLE products (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        type TEXT NOT NULL CHECK (type IN ('produto','servico')),
        name TEXT NOT NULL,
        sku TEXT UNIQUE,
        category TEXT,
        unit_measure TEXT NOT NULL DEFAULT 'un',
        price_cents BIGINT NOT NULL DEFAULT 0 CHECK (price_cents >= 0),
        cost_cents BIGINT NOT NULL DEFAULT 0 CHECK (cost_cents >= 0),
        min_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
        description TEXT,
        active INTEGER NOT NULL DEFAULT 1,
        created_at ${TS},
        updated_at ${TS}
      );

      CREATE TABLE stock (
        product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
        unit_id BIGINT NOT NULL REFERENCES units(id) ON DELETE CASCADE,
        quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
        updated_at ${TS},
        PRIMARY KEY (product_id, unit_id)
      );

      CREATE TABLE events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
        unit_id BIGINT NOT NULL REFERENCES units(id) ON DELETE RESTRICT,
        deal_id BIGINT REFERENCES deals(id) ON DELETE SET NULL,
        event_type TEXT,
        start_at ${D} NOT NULL,
        end_at ${D} NOT NULL,
        duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0),
        guests INTEGER,
        status TEXT NOT NULL DEFAULT 'pre_reserva'
          CHECK (status IN ('pre_reserva','confirmado','realizado','cancelado')),
        discount_cents BIGINT NOT NULL DEFAULT 0 CHECK (discount_cents >= 0),
        total_cents BIGINT NOT NULL DEFAULT 0,
        notes TEXT,
        stock_consumed INTEGER NOT NULL DEFAULT 0,
        cancel_reason TEXT,
        created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at ${TS},
        updated_at ${TS},
        CHECK (end_at > start_at)
      );
      CREATE INDEX idx_events_unit_time ON events(unit_id, start_at, end_at);
      CREATE INDEX idx_events_start ON events(start_at);
      CREATE INDEX idx_events_client ON events(client_id);

      CREATE TABLE stock_movements (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
        unit_id BIGINT NOT NULL REFERENCES units(id) ON DELETE CASCADE,
        type TEXT NOT NULL CHECK (type IN ('entrada','saida','ajuste','transferencia_entrada','transferencia_saida','consumo_evento')),
        quantity DOUBLE PRECISION NOT NULL,
        balance_after DOUBLE PRECISION NOT NULL,
        reason TEXT,
        event_id BIGINT REFERENCES events(id) ON DELETE SET NULL,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at ${TS}
      );
      CREATE INDEX idx_movements_product ON stock_movements(product_id, unit_id);

      CREATE TABLE event_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
        product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
        description TEXT NOT NULL,
        quantity DOUBLE PRECISION NOT NULL CHECK (quantity > 0),
        unit_price_cents BIGINT NOT NULL CHECK (unit_price_cents >= 0)
      );
      CREATE INDEX idx_event_items_event ON event_items(event_id);

      CREATE TABLE blocked_dates (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        date ${D} NOT NULL,
        unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE,
        reason TEXT,
        created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at ${TS}
      );
      CREATE UNIQUE INDEX idx_blocked_unique ON blocked_dates(date, COALESCE(unit_id, 0));

      CREATE TABLE contracts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
        number TEXT NOT NULL UNIQUE,
        content TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'rascunho'
          CHECK (status IN ('rascunho','enviado','assinado','cancelado')),
        public_token TEXT NOT NULL UNIQUE,
        accepted_name TEXT,
        accepted_document TEXT,
        accepted_ip TEXT,
        accepted_at ${D},
        sent_at ${D},
        created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at ${TS},
        updated_at ${TS}
      );
      CREATE INDEX idx_contracts_event ON contracts(event_id);

      CREATE TABLE transactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        type TEXT NOT NULL CHECK (type IN ('receber','pagar')),
        description TEXT NOT NULL,
        category TEXT,
        amount_cents BIGINT NOT NULL CHECK (amount_cents > 0),
        due_date ${D} NOT NULL,
        status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','pago','cancelado')),
        paid_at ${D},
        paid_amount_cents BIGINT,
        payment_method TEXT,
        client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
        event_id BIGINT REFERENCES events(id) ON DELETE SET NULL,
        supplier TEXT,
        document_number TEXT,
        installment TEXT,
        notes TEXT,
        created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at ${TS},
        updated_at ${TS}
      );
      CREATE INDEX idx_transactions_due ON transactions(type, status, due_date);
      CREATE INDEX idx_transactions_paid ON transactions(status, paid_at);
      CREATE INDEX idx_transactions_event ON transactions(event_id);

      CREATE TABLE forms (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token TEXT NOT NULL UNIQUE,
        type TEXT NOT NULL CHECK (type IN ('cadastro','briefing')),
        client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
        event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
        status TEXT NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','respondido')),
        response TEXT,
        expires_at ${D} NOT NULL,
        created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at ${TS},
        responded_at ${D}
      );

      CREATE TABLE whatsapp_messages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
        phone TEXT NOT NULL,
        kind TEXT NOT NULL CHECK (kind IN ('mensagem','contrato','formulario','cobranca')),
        body TEXT NOT NULL,
        mode TEXT NOT NULL CHECK (mode IN ('link','api')),
        status TEXT NOT NULL,
        provider_id TEXT,
        error TEXT,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at ${TS}
      );

      CREATE TABLE settings (
        key TEXT PRIMARY KEY,
        value TEXT
      );

      CREATE TABLE audit_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        action TEXT NOT NULL,
        entity TEXT NOT NULL,
        entity_id BIGINT,
        details TEXT,
        ip TEXT,
        created_at ${TS}
      );
      CREATE INDEX idx_audit_created ON audit_log(created_at);
    `,
  },
  {
    version: 2,
    name: 'fecha as tabelas para a API pública do Supabase',
    // O Supabase publica o schema "public" numa API REST acessível com a chave anônima do projeto.
    // O sistema não usa essa API: só o servidor acessa o banco. Então ligamos o RLS sem nenhuma
    // política (ninguém de fora lê nada) e tiramos os privilégios dos papéis públicos.
    // Em Postgres comum (PGlite, servidor próprio) os papéis anon/authenticated não existem e
    // só o RLS é aplicado, sem efeito para o dono das tabelas.
    sql: `
      DO $$
      DECLARE t text;
      BEGIN
        FOREACH t IN ARRAY ARRAY['users','sessions','units','clients','deals','interactions','products','stock',
          'events','stock_movements','event_items','blocked_dates','contracts','transactions','forms',
          'whatsapp_messages','settings','audit_log','schema_migrations']
        LOOP
          EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        END LOOP;
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
          EXECUTE 'REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated';
          EXECUTE 'REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated';
          EXECUTE 'REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM anon, authenticated';
        END IF;
      END $$;
    `,
  },
];
